apiVersion: v1
kind: Service
metadata:
  name: web-shop-backend-service
  labels:
    app: web-shop-backend
spec:
  selector:
    app: web-shop-backend
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
